#!/usr/bin/env bash
# Exercises deploy/install.sh in temporary paths — no root, no systemd, no
# touching the machine running the test.
#
#   bash test/install_test.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

ok()  { printf '\033[1;32m  ✓\033[0m %s\n' "$*"; }
bad() { printf '\033[1;31m  ✗\033[0m %s\n' "$*"; exit 1; }

run_install() {
	env PREFIX="$WORK" UNIT_DIR="$WORK" ENV_FILE="$WORK/pockterm.env" "$@" \
		bash "$ROOT/deploy/install.sh" >"$WORK/out" 2>&1 || {
		cat "$WORK/out"; bad "installer failed"; }
}

# --- default: a token is generated ---
run_install
grep -q '^POCKTERM_TOKEN=' "$WORK/pockterm.env" || bad "no token generated by default"
[ "$(stat -c '%a' "$WORK/pockterm.env")" = 600 ] || bad "env file is not 0600"
[ "$(stat -c '%a' "$WORK/pockterm.service")" = 644 ] || bad "unit is not 0644"
grep -q 'POCKTERM_TOKEN' "$WORK/pockterm.service" && bad "token leaked into the unit"
ok "default run generates a token, 0600, and keeps it out of the unit"

before="$(md5sum "$WORK/pockterm.env")"
run_install
[ "$before" = "$(md5sum "$WORK/pockterm.env")" ] || bad "second run changed the token"
ok "re-running keeps the token"

# --- mutual TLS: no token at all ---
rm -f "$WORK/pockterm.env" "$WORK/pockterm.service"
run_install POCKTERM_NO_TOKEN=1
if [ -f "$WORK/pockterm.env" ] && grep -q '^POCKTERM_TOKEN=' "$WORK/pockterm.env"; then
	bad "a token was generated despite POCKTERM_NO_TOKEN"
fi
grep -q 'no token generated' "$WORK/out" || bad "the installer did not say it skipped the token"
ok "POCKTERM_NO_TOKEN leaves the install tokenless"

# --- an existing token is never silently discarded ---
printf 'POCKTERM_TOKEN=keepme\n' > "$WORK/pockterm.env"
chmod 600 "$WORK/pockterm.env"
run_install POCKTERM_NO_TOKEN=1
grep -q '^POCKTERM_TOKEN=keepme$' "$WORK/pockterm.env" || bad "existing token was removed"
grep -q 'already has a token' "$WORK/out" || bad "no warning about the existing token"
ok "an existing token survives, with a warning"

echo
printf '\033[1;34m[install-test]\033[0m all checks passed\n'
