#!/usr/bin/env bash
# Exercises deploy/install.sh in temporary paths — no root, no systemd, no
# touching the machine running the test.
#
#   bash test/install_test.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

ok()  { printf '\033[1;32m  ✓\033[0m %s\n' "$*"; }
bad() { printf '\033[1;31m  ✗\033[0m %s\n' "$*"; exit 1; }

# tmux stands in front of the real one on PATH: the installer refuses to run
# without it, and the containers this suite runs in have no reason to carry a
# terminal multiplexer. The stub is never called — only looked up.
mkdir -p "$WORK/bin"
printf '#!/bin/sh\nexit 0\n' > "$WORK/bin/tmux"
chmod +x "$WORK/bin/tmux"
export PATH="$WORK/bin:$PATH"

# The session root defaults to the served account's home, which is the machine
# running the test. Every run points it somewhere disposable instead; the two
# checks that care about the default say so themselves.
ROOTDIR="$WORK/projects"
mkdir -p "$ROOTDIR"

# run_install VAR=value... [-- script arguments...]
#
# Everything before `--` is environment for the installer, everything after it
# is arguments to the script itself. Without the separator an option would be
# handed to `env`, which reads it as the command to run.
install_run() {
	local envs=() args=()
	while [ $# -gt 0 ]; do
		if [ "$1" = "--" ]; then shift; args=("$@"); break; fi
		envs+=("$1"); shift
	done
	env PREFIX="$WORK" UNIT_DIR="$WORK" ENV_FILE="$WORK/pockterm.env" \
		POCKTERM_SESSION_DIR="$ROOTDIR" ${envs[@]+"${envs[@]}"} \
		bash "$ROOT/deploy/install.sh" ${args[@]+"${args[@]}"} >"$WORK/out" 2>&1
}

run_install() {
	install_run "$@" || { cat "$WORK/out"; bad "installer failed"; }
}

# run_install_expecting_failure runs it the same way but wants a non-zero exit.
run_install_expecting_failure() {
	if install_run "$@"; then
		cat "$WORK/out"; bad "the installer succeeded where it should have refused"
	fi
}

# --- default: a token is generated ---
run_install
grep -q '^POCKTERM_TOKEN=' "$WORK/pockterm.env" || bad "no token generated by default"
[ "$(stat -c '%a' "$WORK/pockterm.env")" = 600 ] || bad "env file is not 0600"
[ "$(stat -c '%a' "$WORK/pockterm.service")" = 644 ] || bad "unit is not 0644"
grep -q 'POCKTERM_TOKEN' "$WORK/pockterm.service" && bad "token leaked into the unit"
ok "default run generates a token, 0600, and keeps it out of the unit"

before="$(md5sum "$WORK/pockterm.env")"
run_install
[ "$before" = "$(md5sum "$WORK/pockterm.env")" ] || bad "second run changed the token"
ok "re-running keeps the token"

# --- mutual TLS: no token at all ---
rm -f "$WORK/pockterm.env" "$WORK/pockterm.service"
run_install POCKTERM_NO_TOKEN=1
if [ -f "$WORK/pockterm.env" ] && grep -q '^POCKTERM_TOKEN=' "$WORK/pockterm.env"; then
	bad "a token was generated despite POCKTERM_NO_TOKEN"
fi
grep -q 'no token generated' "$WORK/out" || bad "the installer did not say it skipped the token"
ok "POCKTERM_NO_TOKEN leaves the install tokenless"

# --- an existing token is never silently discarded ---
printf 'POCKTERM_TOKEN=keepme\n' > "$WORK/pockterm.env"
chmod 600 "$WORK/pockterm.env"
run_install POCKTERM_NO_TOKEN=1
grep -q '^POCKTERM_TOKEN=keepme$' "$WORK/pockterm.env" || bad "existing token was removed"
grep -q 'already has a token' "$WORK/out" || bad "no warning about the existing token"
ok "an existing token survives, with a warning"

# --- the install ends with something to act on, not with homework ---
rm -f "$WORK/pockterm.env" "$WORK/pockterm.service"
run_install
token="$(sed -n 's/^POCKTERM_TOKEN=//p' "$WORK/pockterm.env")"
grep -q "http://127.0.0.1:8130/?token=$token" "$WORK/out" || bad "no ready-to-open local link"
grep -q 'POCKTERM_LISTEN=0.0.0.0' "$WORK/out" || bad "no hint about reaching it from a phone"
ok "a loopback install prints the local link and how to widen it"

# A wildcard listener is the try-it-from-the-phone case: the address of this
# machine plus a QR to point a camera at.
run_install POCKTERM_LISTEN=0.0.0.0:8130
if grep -q 'could not work out this machine' "$WORK/out"; then
	ok "no reachable address here, and the installer says so instead of guessing"
else
	grep -q "token=$token" "$WORK/out" || bad "no link with the token for the phone"
	grep -q '█' "$WORK/out" || bad "no QR code printed"
	grep -q '127.0.0.1' "$WORK/out" && bad "handed out loopback as the phone's address"
	ok "a wildcard install prints a scannable link on this machine's address"
fi

# With a public URL the QR is the real thing, TLS and all.
run_install POCKTERM_PUBLIC_URL=https://cc.example
grep -q "https://cc.example/?token=$token" "$WORK/out" || bad "the public URL did not reach the QR"
ok "POCKTERM_PUBLIC_URL is what gets encoded when it is set"

# --- the "+" button works without anyone having read the README ---
# A fresh install leaves a phone with no session and no way to start one unless
# the session Makefile is in place and the server has been told where it is.
grep -q 'pockterm-sessions' "$ROOTDIR/Makefile" || bad "no session Makefile in the projects root"
grep -q "^POCKTERM_SESSION_DIR=$ROOTDIR$" "$WORK/pockterm.env" || bad "POCKTERM_SESSION_DIR did not reach the env file"
ok "the session Makefile is installed and pointed at"

# The file is meant to be edited, so a second run must not undo the editing —
# and the variable must not accumulate a second line, which is what an
# `echo >>` in a README does.
printf '\n# mine\n' >> "$ROOTDIR/Makefile"
run_install
grep -q '^# mine$' "$ROOTDIR/Makefile" || bad "the installer overwrote an edited session Makefile"
[ "$(grep -c '^POCKTERM_SESSION_DIR=' "$WORK/pockterm.env")" = 1 ] || bad "POCKTERM_SESSION_DIR was written twice"
grep -q 'yours to edit' "$WORK/out" || bad "the installer did not say it kept the Makefile"
ok "an edited session Makefile survives, and the variable is written once"

# Somebody else's Makefile is not ours to read targets into: `make claude` in it
# is an unknown command rather than a session, so neither it nor the variable is
# touched and the reason is printed.
FOREIGN="$WORK/foreign"
mkdir -p "$FOREIGN"
printf 'all:\n\t@echo not pockterm\n' > "$FOREIGN/Makefile"
run_install POCKTERM_SESSION_DIR="$FOREIGN" ENV_FILE="$WORK/foreign.env"
grep -q 'not pockterm' "$FOREIGN/Makefile" || bad "a foreign Makefile was overwritten"
grep -q '^POCKTERM_SESSION_DIR=' "$WORK/foreign.env" && bad "pointed the + button at a Makefile that is not ours"
grep -q 'is not pockterm' "$WORK/out" || bad "no word about the foreign Makefile"
ok "a Makefile that is not pockterm's is left alone, and said so"

# make reads GNUmakefile before Makefile, so writing next to one would install a
# file make never opens and report success.
GNUDIR="$WORK/gnu"
mkdir -p "$GNUDIR"
printf 'all:\n\t@echo gnu\n' > "$GNUDIR/GNUmakefile"
run_install POCKTERM_SESSION_DIR="$GNUDIR" ENV_FILE="$WORK/gnu.env"
[ -f "$GNUDIR/Makefile" ] && bad "installed a Makefile that make would never read"
ok "a GNUmakefile counts as the Makefile that is already there"

# `off` is the server's own word for "the page may not start sessions", so the
# installer reads it as an answer rather than as a directory it cannot find.
run_install POCKTERM_SESSION_DIR=off ENV_FILE="$WORK/off.env"
grep -q 'sessions are off' "$WORK/out" || bad "POCKTERM_SESSION_DIR=off was not understood"
grep -q '^POCKTERM_SESSION_DIR=' "$WORK/off.env" && bad "off was written to the env file as a directory"
ok "POCKTERM_SESSION_DIR=off is an answer, not a missing directory"

run_install POCKTERM_NO_SESSIONS=1 POCKTERM_SESSION_DIR="$WORK/none" ENV_FILE="$WORK/none.env"
[ -f "$WORK/none/Makefile" ] && bad "POCKTERM_NO_SESSIONS still installed a Makefile"
grep -q 'POCKTERM_NO_SESSIONS' "$WORK/out" || bad "the installer did not say it skipped the sessions setup"
ok "POCKTERM_NO_SESSIONS leaves the projects root alone"

# --- what the host must have, checked before anything is installed ---
# Without tmux there is nothing to serve, and an empty session list on a phone
# looks like a broken terminal rather than a missing package.
run_install_expecting_failure REQUIRE_TMUX=pockterm-no-such-tool
grep -q 'pockterm-no-such-tool is not installed' "$WORK/out" || bad "no word about the missing tmux"
grep -qE 'apt-get install|dnf install|pacman -S|zypper install|apk add|with your package manager' "$WORK/out" ||
	bad "the refusal did not say how to install it"
ok "a host without tmux is refused, with the command that fixes it"

# make is only the "+" button, so its absence is a warning and the install goes on.
run_install REQUIRE_MAKE=pockterm-no-such-tool
grep -q 'pockterm-no-such-tool is not installed' "$WORK/out" || bad "no warning about the missing make"
grep -q 'binary → ' "$WORK/out" || bad "a missing make stopped the install"
ok "a host without make is warned, not refused"

# --- --tg pairs Telegram inside the install, and a failure is not fatal ---
# Port 1 refuses instantly, which is what a bot token that cannot be checked
# looks like from here. What matters is that the rest of the install stands.
run_install POCKTERM_TG_TOKEN=not-a-real-token POCKTERM_TG_API=http://127.0.0.1:1 \
	ENV_FILE="$WORK/tg.env" -- --tg
grep -q '^POCKTERM_TG_TOKEN=' "$WORK/tg.env" && bad "a token that was never verified reached the env file"
grep -q 'telegram is not configured' "$WORK/out" || bad "no warning that the pairing failed"
grep -q 'here: http://127.0.0.1:8130/' "$WORK/out" || bad "a failed pairing took the rest of the install with it"
ok "--tg pairs Telegram in the install, and its failure ends only itself"

# --- installing from a published release, no toolchain needed ---
# A local directory stands in for the release page: curl reads file:// URLs,
# so this exercises the real download path without a network.
REL="$WORK/release"
mkdir -p "$REL"
arch="$(uname -m)"
case "$arch" in
	x86_64 | amd64) arch=amd64 ;;
	aarch64 | arm64) arch=arm64 ;;
esac
cp "$WORK/pockterm" "$REL/pockterm-linux-$arch"
(cd "$REL" && sha256sum "pockterm-linux-$arch" > SHA256SUMS)

rm -f "$WORK/pockterm"
run_install POCKTERM_FROM_RELEASE=1 POCKTERM_RELEASE_BASE="file://$REL"
[ -x "$WORK/pockterm" ] || bad "the release binary was not installed"
grep -q 'downloaded and verified' "$WORK/out" || bad "the installer did not verify the download"
ok "a published release installs without a go toolchain"

# --- a tampered binary is not installed ---
printf 'not the binary you published\n' > "$REL/pockterm-linux-$arch"
rm -f "$WORK/pockterm"
if env PREFIX="$WORK" UNIT_DIR="$WORK" ENV_FILE="$WORK/pockterm.env" \
	POCKTERM_FROM_RELEASE=1 POCKTERM_RELEASE_BASE="file://$REL" \
	bash "$ROOT/deploy/install.sh" >"$WORK/out" 2>&1; then
	bad "a binary that does not match SHA256SUMS was installed anyway"
fi
grep -q 'checksum mismatch' "$WORK/out" || bad "no word about the checksum in the failure"
[ -x "$WORK/pockterm" ] && bad "the tampered binary reached $WORK/pockterm"
ok "a download that does not match the published sums is refused"

echo
printf '\033[1;34m[install-test]\033[0m all checks passed\n'
